DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS access_tokens CASCADE;
DROP INDEX IF EXISTS idx_token;
DROP INDEX IF EXISTS idx_level;

DROP TABLE IF EXISTS hosts CASCADE;
DROP INDEX IF EXISTS idx_name;
DROP INDEX IF EXISTS idx_tags;
DROP INDEX IF EXISTS idx_data;
