DROP TABLE IF EXISTS ts_watchers_q1_2016 CASCADE;
DROP TABLE IF EXISTS ts_watchers_q2_2016 CASCADE;
DROP TABLE IF EXISTS ts_watchers_q3_2016 CASCADE;
DROP TABLE IF EXISTS ts_watchers_q4_2016 CASCADE;
